name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '30 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch latest data
      run: |-
        curl -L https://www.welt.de/finanzen/verbraucher/article241411145/Black-Friday-Diese-attraktiven-Angebote-gibt-es-bereits-jetzt-bei-Amazon.html > article.html
        FROM=$(grep -n '"author" : {' article.html | awk '{print $1}' FS=":")
        TO=$(grep -n '</script> <img' article.html | awk '{print $1}' FS=":")
        TO=$(expr $TO - 1)
        FILENAME=$(date '+%Y-%m-%d %H:%M:%S').txt
        sed -n "${FROM},${TO}p" article.html > "${FILENAME}"
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
